In [2]:
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.columns = df.columns.str.lower()

In [5]:
df.describe().round(2)

       passengerid  survived  pclass     age   sibsp   parch    fare
count       891.00    891.00  891.00  714.00  891.00  891.00  891.00
mean        446.00      0.38    2.31   29.70    0.52    0.38   32.20
std         257.35      0.49    0.84   14.53    1.10    0.81   49.69
min           1.00      0.00    1.00    0.42    0.00    0.00    0.00
25%         223.50      0.00    2.00   20.12    0.00    0.00    7.91
50%         446.00      0.00    3.00   28.00    0.00    0.00   14.45
75%         668.50      1.00    3.00   38.00    1.00    0.00   31.00
max         891.00      1.00    3.00   80.00    8.00    6.00  512.33

In [6]:
features = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare','embarked', 'survived']
df = df[features]
df.isnull().sum()
df.embarked = df.embarked.fillna('Unknown')
df.isnull().sum()

pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      0
survived      0
dtype: int64

In [7]:
df.pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [8]:
pclass_map = {
    1: 'first',
    2: 'second',
    3: 'third'
}
df.pclass = df.pclass.map(pclass_map)

In [9]:
df.head()

  pclass     sex   age  sibsp  parch     fare embarked  survived
0  third    male  22.0      1      0   7.2500        S         0
1  first  female  38.0      1      0  71.2833        C         1
2  third  female  26.0      0      0   7.9250        S         1
3  first  female  35.0      1      0  53.1000        S         1
4  third    male  35.0      0      0   8.0500        S         0

In [16]:
df['family_size'] = df.sibsp + df.parch + 1
df = df.drop(columns=['sibsp', 'parch'])
df.head()

  pclass     sex   age     fare embarked  survived  family_size
0  third    male  22.0   7.2500        S         0            2
1  first  female  38.0  71.2833        C         1            2
2  third  female  26.0   7.9250        S         1            1
3  first  female  35.0  53.1000        S         1            2
4  third    male  35.0   8.0500        S         0            1

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [13]:
mean_age = df_train.age.mean()

In [14]:
df_train['age'] = df_train.age.fillna(mean_age)
df_val['age'] = df_val.age.fillna(mean_age)
df_test['age'] = df_test.age.fillna(mean_age)

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [15]:
y_train = df_train.survived.values
y_val = df_val.survived.values
y_test = df_test.survived.values

del df_train['survived']
del df_val['survived']
del df_test['survived']